export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

export const FETCH_MEALS_START = 'FETCH_MEALS_START';
export const FETCH_MEALS_FAIL = 'FETCH_MEALS_FAIL';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS'

export const FETCH_RANDOM_START = 'FETCH_RANDOM_START';
export const FETCH_RANDOM_FAIL = 'FETCH_RANDOM_FAIL';
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS';


export const FETCH_MEAL_START = 'FETCH_MEAL_START';
export const FETCH_MEAL_FAIL = 'FETCH_MEAL_FAIL';
export const FETCH_MEAL_SUCCESS = 'FETCH_MEAL_SUCCESS';


export const FETCH_SIMILAR_START = 'FETCH_SIMILAR_START';
export const FETCH_SIMILAR_FAIL = 'FETCH_SIMILAR_FAIL';
export const FETCH_SIMILAR_SUCCESS = 'FETCH_SIMILAR_SUCCESS';


export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'


export const SIGN_OUT_SUCCESS = 'SIGNOUT_SUCCESS'

export const SIGN_UP_START = 'SIGH_UP_START'
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'