export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

export const FETCH_MEALS_START = 'FETCH_MEALS_START';
export const FETCH_MEALS_FAIL = 'FETCH_MEALS_FAIL';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS'

export const FETCH_RANDOM_START = 'FETCH_RANDOM_START';
export const FETCH_RANDOM_FAIL = 'FETCH_RANDOM_FAIL';
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS';
